package:
  name: quadpy
  version: 0.10.7

source:
  fn: v0.10.7.tar.gz
  url: https://github.com/nschloe/quadpy/archive/v0.10.7.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib >=2.1.0
    - numpy >=1.13.3
    - orthopy ==0.2.0
    - scipy >=1.0.0
    - sympy >=1.1.1

test:
  imports:
    - quadpy
    
about:
  home: https://github.com/nschloe/quadpy
  license: MIT License
  summary: Numerical integration (quadrature, cubature) in Python

